name: "Lint PR"

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          subjectPattern: ^((?<!([A-Z]{1,10})-?)[A-Z]+-\d+)\s-\s.+$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# asdf
