name: Test secret
on:
  # pull_request_target:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize
  #     - reopened
  # pull_request:
  #   branches:
  #     - main
  push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mccorkle-co/test-repo1
          token: ${{ secrets.GTS_GITHUB_TOKEN }}

      - name: create file
        shell: pwsh
        run: |
          "hello world" | Out-File -FilePath .\test.txt -Append

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Testing file
